# KiraSMP Configuration File
settings:
  enableHomes: true         # Whether players can set homes
  maxHomes: 5               # Maximum number of homes a player can set
  weatherVoteThreshold: 0.5 # Percentage of players required to change weather
  sleepVoteThreshold: 0.5   # Percentage of players required to skip night
