name: KiraSMP
version: '2.0'
main: np.com.birajrai.KiraSMP
api-version: '1.21'
description: A KiraSMP plugin with essential features and XP economy
author: birajrai

commands:
  sethome:
    description: Set your home location
    usage: /sethome
    permission: kirasmp.home.set
  home:
    description: Teleport to your home
    usage: /home
    permission: kirasmp.home.teleport
  tpa:
    description: Send a teleport request to another player
    usage: /tpa <player>
    permission: kirasmp.tpa
  tpaccept:
    description: Accept a pending teleport request
    usage: /tpaccept
    permission: kirasmp.tpa.accept
  addwarp:
    description: Create a new warp point
    usage: /addwarp <name>
    permission: kirasmp.warp.create
  warp:
    description: Teleport to a warp point
    usage: /warp <name>
    permission: kirasmp.warp.use
  warps:
    description: List all available warps
    usage: /warps
    permission: kirasmp.warp.list
  rtp:
    description: Teleport to a random location
    usage: /rtp
    permission: kirasmp.rtp
  weathervote:
    description: Vote to change the weather
    usage: /weathervote
    permission: kirasmp.vote.weather
  sleepvote:
    description: Vote to skip the night
    usage: /sleepvote
    permission: kirasmp.vote.sleep
  skin:
    description: Change your skin to another player's skin
    usage: /skin <playername>
    permission: kirasmp.skin
    