vote-threshold: 0.5
messages:
  sethome: "Home set successfully!"
  home: "Teleported to home!"
  spawn: "Teleported to spawn!"
  tpa-sent: "Teleport request sent to {player}."
  tpa-received: "{player} has requested to teleport to you. Type /tpaccept to accept."
  tpaccept: "Teleport request accepted."
  weather-changed: "Weather changed by vote!"
  sleep-skipped: "Night skipped by vote!"
